sonar.projectName=Cloud Infrastructure Platform
sonar.projectKey=shivamshashank_cloud-infrastructure-platform
sonar.organization=shivamshashank
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/*.tar,**/.cache/**,coverage.out
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
